version: "3.8"
services:
    mkdocs:
        build: ./docker/docs
        container_name: mkdocs-m242
        restart: unless-stopped
        volumes:
            - ./docs:/docs/docs
            - ./docs/mkdocs.yml:/docs/mkdocs.yml
        ports:
            - "13555:8000"
